### ISSUE TITLE
异常

### ISSUE THREAD

**Issue by SeekMyCosmic** [hejunlin2013/LivePlayback#4]
java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.hejunlin.liveplayback-1/lib/x86/libijkffmpeg.so: has text relocations

**Comment by smartyuge** [comment]
编译x86的 so，就可以

**Comment by SeekMyCosmic** [comment]
谢谢! 我试下。

2017-08-25 9:37 GMT+08:00, 逆流的鱼yuiop <notifications@github.com>:
